/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as DoctorDashboardRouteImport } from './routes/doctor/dashboard'
import { Route as DoctorLoginRouteImport } from './routes/doctor/login'
import { Route as PatientAppointmentsRouteImport } from './routes/patient/appointments'
import { Route as PatientAssistantRouteImport } from './routes/patient/assistant'
import { Route as PatientAuthRouteImport } from './routes/patient/auth'
import { Route as PatientEmergencyRouteImport } from './routes/patient/emergency'
import { Route as PatientHomeRouteImport } from './routes/patient/home'
import { Route as PatientHospitalsRouteImport } from './routes/patient/hospitals'
import { Route as PatientProfileRouteImport } from './routes/patient/profile'
import { Route as PatientReportsRouteImport } from './routes/patient/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorLoginRoute = DoctorLoginRouteImport.update({
  id: '/doctor/login',
  path: '/doctor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/patient/assistant',
  path: '/patient/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAuthRoute = PatientAuthRouteImport.update({
  id: '/patient/auth',
  path: '/patient/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEmergencyRoute = PatientEmergencyRouteImport.update({
  id: '/patient/emergency',
  path: '/patient/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHomeRoute = PatientHomeRouteImport.update({
  id: '/patient/home',
  path: '/patient/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHospitalsRoute = PatientHospitalsRouteImport.update({
  id: '/patient/hospitals',
  path: '/patient/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/patient/reports',
  path: '/patient/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/auth': typeof PatientAuthRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/hospitals': typeof PatientHospitalsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/auth': typeof PatientAuthRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/hospitals': typeof PatientHospitalsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/auth': typeof PatientAuthRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/hospitals': typeof PatientHospitalsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/assistant'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/auth'
    | '/patient/emergency'
    | '/patient/home'
    | '/patient/hospitals'
    | '/patient/profile'
    | '/patient/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/assistant'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/auth'
    | '/patient/emergency'
    | '/patient/home'
    | '/patient/hospitals'
    | '/patient/profile'
    | '/patient/reports'
  id:
    | '__root__'
    | '/'
    | '/api/assistant'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/auth'
    | '/patient/emergency'
    | '/patient/home'
    | '/patient/hospitals'
    | '/patient/profile'
    | '/patient/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorLoginRoute: typeof DoctorLoginRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientAuthRoute: typeof PatientAuthRoute
  PatientEmergencyRoute: typeof PatientEmergencyRoute
  PatientHomeRoute: typeof PatientHomeRoute
  PatientHospitalsRoute: typeof PatientHospitalsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/login': {
      id: '/doctor/login'
      path: '/doctor/login'
      fullPath: '/doctor/login'
      preLoaderRoute: typeof DoctorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/patient/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/auth': {
      id: '/patient/auth'
      path: '/patient/auth'
      fullPath: '/patient/auth'
      preLoaderRoute: typeof PatientAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/emergency': {
      id: '/patient/emergency'
      path: '/patient/emergency'
      fullPath: '/patient/emergency'
      preLoaderRoute: typeof PatientEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/home': {
      id: '/patient/home'
      path: '/patient/home'
      fullPath: '/patient/home'
      preLoaderRoute: typeof PatientHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/hospitals': {
      id: '/patient/hospitals'
      path: '/patient/hospitals'
      fullPath: '/patient/hospitals'
      preLoaderRoute: typeof PatientHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/patient/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorLoginRoute: DoctorLoginRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientAssistantRoute: PatientAssistantRoute,
  PatientAuthRoute: PatientAuthRoute,
  PatientEmergencyRoute: PatientEmergencyRoute,
  PatientHomeRoute: PatientHomeRoute,
  PatientHospitalsRoute: PatientHospitalsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
