/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as ApiCaseSummaryRouteImport } from './routes/api/case-summary'
import { Route as DoctorDashboardRouteImport } from './routes/doctor/dashboard'
import { Route as DoctorLoginRouteImport } from './routes/doctor/login'
import { Route as PatientAppointmentsRouteImport } from './routes/patient/appointments'
import { Route as PatientAssistantRouteImport } from './routes/patient/assistant'
import { Route as PatientAuthRouteImport } from './routes/patient/auth'
import { Route as PatientEmergencyRouteImport } from './routes/patient/emergency'
import { Route as PatientHomeRouteImport } from './routes/patient/home'
import { Route as PatientHospitalsRouteImport } from './routes/patient/hospitals'
import { Route as PatientProfileRouteImport } from './routes/patient/profile'
import { Route as PatientReportsRouteImport } from './routes/patient/reports'
import { Route as ApiAuthDoctorRouteImport } from './routes/api/auth/doctor'
import { Route as ApiCasesIndexRouteImport } from './routes/api/cases/index'
import { Route as ApiDocumentsAnalyzeRouteImport } from './routes/api/documents/analyze'
import { Route as ApiCasesCaseIdIndexRouteImport } from './routes/api/cases/$caseId/index'
import { Route as ApiCasesCaseIdDocumentsDocIdRouteImport } from './routes/api/cases/$caseId/documents/$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaseSummaryRoute = ApiCaseSummaryRouteImport.update({
  id: '/api/case-summary',
  path: '/api/case-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorLoginRoute = DoctorLoginRouteImport.update({
  id: '/doctor/login',
  path: '/doctor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/patient/assistant',
  path: '/patient/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAuthRoute = PatientAuthRouteImport.update({
  id: '/patient/auth',
  path: '/patient/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEmergencyRoute = PatientEmergencyRouteImport.update({
  id: '/patient/emergency',
  path: '/patient/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHomeRoute = PatientHomeRouteImport.update({
  id: '/patient/home',
  path: '/patient/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHospitalsRoute = PatientHospitalsRouteImport.update({
  id: '/patient/hospitals',
  path: '/patient/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/patient/reports',
  path: '/patient/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDoctorRoute = ApiAuthDoctorRouteImport.update({
  id: '/api/auth/doctor',
  path: '/api/auth/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesIndexRoute = ApiCasesIndexRouteImport.update({
  id: '/api/cases/',
  path: '/api/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsAnalyzeRoute = ApiDocumentsAnalyzeRouteImport.update({
  id: '/api/documents/analyze',
  path: '/api/documents/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesCaseIdIndexRoute = ApiCasesCaseIdIndexRouteImport.update({
  id: '/api/cases/$caseId/',
  path: '/api/cases/$caseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCasesCaseIdDocumentsDocIdRoute =
  ApiCasesCaseIdDocumentsDocIdRouteImport.update({
    id: '/api/cases/$caseId/documents/$docId',
    path: '/api/cases/$caseId/documents/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/case-summary': typeof ApiCaseSummaryRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/auth': typeof PatientAuthRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/hospitals': typeof PatientHospitalsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/api/auth/doctor': typeof ApiAuthDoctorRoute
  '/api/documents/analyze': typeof ApiDocumentsAnalyzeRoute
  '/api/cases/': typeof ApiCasesIndexRoute
  '/api/cases/$caseId/': typeof ApiCasesCaseIdIndexRoute
  '/api/cases/$caseId/documents/$docId': typeof ApiCasesCaseIdDocumentsDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/case-summary': typeof ApiCaseSummaryRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/auth': typeof PatientAuthRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/hospitals': typeof PatientHospitalsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/api/auth/doctor': typeof ApiAuthDoctorRoute
  '/api/documents/analyze': typeof ApiDocumentsAnalyzeRoute
  '/api/cases': typeof ApiCasesIndexRoute
  '/api/cases/$caseId': typeof ApiCasesCaseIdIndexRoute
  '/api/cases/$caseId/documents/$docId': typeof ApiCasesCaseIdDocumentsDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/case-summary': typeof ApiCaseSummaryRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/auth': typeof PatientAuthRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/hospitals': typeof PatientHospitalsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/api/auth/doctor': typeof ApiAuthDoctorRoute
  '/api/documents/analyze': typeof ApiDocumentsAnalyzeRoute
  '/api/cases/': typeof ApiCasesIndexRoute
  '/api/cases/$caseId/': typeof ApiCasesCaseIdIndexRoute
  '/api/cases/$caseId/documents/$docId': typeof ApiCasesCaseIdDocumentsDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/assistant'
    | '/api/case-summary'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/auth'
    | '/patient/emergency'
    | '/patient/home'
    | '/patient/hospitals'
    | '/patient/profile'
    | '/patient/reports'
    | '/api/auth/doctor'
    | '/api/documents/analyze'
    | '/api/cases/'
    | '/api/cases/$caseId/'
    | '/api/cases/$caseId/documents/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/assistant'
    | '/api/case-summary'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/auth'
    | '/patient/emergency'
    | '/patient/home'
    | '/patient/hospitals'
    | '/patient/profile'
    | '/patient/reports'
    | '/api/auth/doctor'
    | '/api/documents/analyze'
    | '/api/cases'
    | '/api/cases/$caseId'
    | '/api/cases/$caseId/documents/$docId'
  id:
    | '__root__'
    | '/'
    | '/api/assistant'
    | '/api/case-summary'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/auth'
    | '/patient/emergency'
    | '/patient/home'
    | '/patient/hospitals'
    | '/patient/profile'
    | '/patient/reports'
    | '/api/auth/doctor'
    | '/api/documents/analyze'
    | '/api/cases/'
    | '/api/cases/$caseId/'
    | '/api/cases/$caseId/documents/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiCaseSummaryRoute: typeof ApiCaseSummaryRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorLoginRoute: typeof DoctorLoginRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientAuthRoute: typeof PatientAuthRoute
  PatientEmergencyRoute: typeof PatientEmergencyRoute
  PatientHomeRoute: typeof PatientHomeRoute
  PatientHospitalsRoute: typeof PatientHospitalsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
  ApiAuthDoctorRoute: typeof ApiAuthDoctorRoute
  ApiDocumentsAnalyzeRoute: typeof ApiDocumentsAnalyzeRoute
  ApiCasesIndexRoute: typeof ApiCasesIndexRoute
  ApiCasesCaseIdIndexRoute: typeof ApiCasesCaseIdIndexRoute
  ApiCasesCaseIdDocumentsDocIdRoute: typeof ApiCasesCaseIdDocumentsDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/case-summary': {
      id: '/api/case-summary'
      path: '/api/case-summary'
      fullPath: '/api/case-summary'
      preLoaderRoute: typeof ApiCaseSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/login': {
      id: '/doctor/login'
      path: '/doctor/login'
      fullPath: '/doctor/login'
      preLoaderRoute: typeof DoctorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/patient/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/auth': {
      id: '/patient/auth'
      path: '/patient/auth'
      fullPath: '/patient/auth'
      preLoaderRoute: typeof PatientAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/emergency': {
      id: '/patient/emergency'
      path: '/patient/emergency'
      fullPath: '/patient/emergency'
      preLoaderRoute: typeof PatientEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/home': {
      id: '/patient/home'
      path: '/patient/home'
      fullPath: '/patient/home'
      preLoaderRoute: typeof PatientHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/hospitals': {
      id: '/patient/hospitals'
      path: '/patient/hospitals'
      fullPath: '/patient/hospitals'
      preLoaderRoute: typeof PatientHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/patient/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/doctor': {
      id: '/api/auth/doctor'
      path: '/api/auth/doctor'
      fullPath: '/api/auth/doctor'
      preLoaderRoute: typeof ApiAuthDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/': {
      id: '/api/cases/'
      path: '/api/cases'
      fullPath: '/api/cases/'
      preLoaderRoute: typeof ApiCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/analyze': {
      id: '/api/documents/analyze'
      path: '/api/documents/analyze'
      fullPath: '/api/documents/analyze'
      preLoaderRoute: typeof ApiDocumentsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/$caseId/': {
      id: '/api/cases/$caseId/'
      path: '/api/cases/$caseId'
      fullPath: '/api/cases/$caseId/'
      preLoaderRoute: typeof ApiCasesCaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/$caseId/documents/$docId': {
      id: '/api/cases/$caseId/documents/$docId'
      path: '/api/cases/$caseId/documents/$docId'
      fullPath: '/api/cases/$caseId/documents/$docId'
      preLoaderRoute: typeof ApiCasesCaseIdDocumentsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiCaseSummaryRoute: ApiCaseSummaryRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorLoginRoute: DoctorLoginRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientAssistantRoute: PatientAssistantRoute,
  PatientAuthRoute: PatientAuthRoute,
  PatientEmergencyRoute: PatientEmergencyRoute,
  PatientHomeRoute: PatientHomeRoute,
  PatientHospitalsRoute: PatientHospitalsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
  ApiAuthDoctorRoute: ApiAuthDoctorRoute,
  ApiDocumentsAnalyzeRoute: ApiDocumentsAnalyzeRoute,
  ApiCasesIndexRoute: ApiCasesIndexRoute,
  ApiCasesCaseIdIndexRoute: ApiCasesCaseIdIndexRoute,
  ApiCasesCaseIdDocumentsDocIdRoute: ApiCasesCaseIdDocumentsDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
